### PR TITLE
More detailed description of the folder structure

### PR DESCRIPTION
**Pull request by dschulten**
with initial steps to create responses manually.

### CODE REVIEW

**Comment by smollweide** [comment]
thanks @dschulten for this great documentation

**Comment by dschulten** [comment]
thanks, will do next time

**Comment by dschulten** [comment]
My pull request contained a description of the ui, in addition to the description of the folder structure itself. I just realized that there is an bullet point in the doc list that does not point to any documentation:

* API documentation UI

Should I create a readme-ui-documentation.md, move the descripton of the ui in readme-folder-structure.md to that new file and link it from the root readme?

**Comment by smollweide** [comment]
That would be great. Thanks a lot :)

**Pull request merged**
