### PR TITLE
Placeholder at uri first level

### PR DESCRIPTION
**Pull request by yael-lorenzo-olx**
The idea is to fulfil a requirement where the first part of the uri path (what would be the "group" directory in the folder structure) is a dynamic path param. Something like:
localhost:3001/{apiVersion}/somethingElse.

The request has been made by @anabella-spinelli-olx.

The demo part is included but tests are not made. 
Eg. http://localhost:3001/pu/1/available

The real file changes are.
- demo/index.js
- lib/controller/MockController.js
- lib/defaults/options-defaults.js

### CODE REVIEW

**Comment by smollweide** [comment]
Thanks @yael-lorenzo-olx,
but it's already fixed with: a7ab599

**Comment by yael-lorenzo-olx** [comment]
Hi, I saw it previous my PR but could not run with the config I had. I will try again. Thanks for the quick reply!

**Comment by smollweide** [comment]
Okay. If my fix will not help feel free to create a new issue with a description and your config.

**Comment by yael-lorenzo-olx** [comment]
I have made an empty value of urlPath: '' in options-defaults.js and made a folder named #{po} under rest folder such as you have defined the place holder concept under products in the demo folder. Is there something else. 

I am trying to get it working on localhost:3001/{any value but products | search } with GET

**Comment by smollweide** [comment]
It seems you try to get a response with url `http:localhost:3001/:something`.
Currently that's not possible because that is not an usual implementation of an rest api.
Usually you have an path part which describes the version number `http:localhost:3001/rest/v1` and a part which defines the response like `users/:userId`. You can compare it with SQL `SELECT * FROM users WHERE id = 'userId';`. In your example the first level placeholder is `po` which don't help me to find your idea.

Example with swagger: http://petstore.swagger.io/

Can you describe what `po` means? Did I missed a case where a dynamic first level URI part is needed?

**Comment by yael-lorenzo-olx** [comment]
Hey again, **po** does not have a meaning, it is "product object" variable shortener. 

In my PR it is possible what you describe. 
The requirement is this first [comment](https://github.com/smollweide/node-mock-server/issues/36)

I understand the idea of what you describe regarding normal behavior.

We have a provider which API url starts with a version number. We would love to manage any version number. 
The issue is that we dont know the version of the api provided.

The scenarios in the DEMO folder that we can cover are intially are
- http://localhost:3001/unkown_version_number/variable_value (this will match our requirement)
- http://localhost:3001/products/1234 (also working from your initial demo)
- The other examples you wrote 👍 

**File structure:**
 + #{po}
     + #
        + GET
           + ...
     + #{otherVar}
        + GET
           + ...
 + products
    + ...
 + search ...

The logic would be, if the unkown_version_number != from any first folder declared as static, the mock under this folder would be used.

So, with http://localhost:3001/v13/definitions

The first path I am interested in is v13.
Does it match any folder in ( #{po}, products, search )?
No.
The #{po} must be used.  And that is all.

As wee see it, we cannot use more than one variable "folder".
Sub folders continue with the logic you have already implemented.

Is it a little bit clearer?

**Pull request closed without merging**
